### ISSUE TITLE
golang v11 and mod support

### ISSUE THREAD

**Issue by llonchj** [DATA-DOG/godog#136]
I am unable to run godog successfully in a project outside GOPATH that uses the new go modules.

```
failed to compile testmain package: exit status 2 - output: /var/folders/x4/s1l6gz3x7b5fqvbnbfj80zn40000gn/T/go-build077117674/b001/_testmain.go:5:2: can't find import: "_/Users/myself/myproject"
```

Any ideas on what I am doing wrong?

**Comment by l3pp4rd** [comment]
Hi, I haven't tested the go11 modules yet, that may be the reason, for now I suggest to include TestMain function so you could run it with `go test` together. I will find some time later for adding module support

**Comment by llonchj** [comment]
@l3pp4rd `go test` works well. Thanks!

**Comment by l3pp4rd** [comment]
some findings so far, if anyone uses `godog` with new `go mod` feature, it may fail with `permission denied` errors while trying to install package dependencies. this is fixed in `go master` branch, see https://github.com/golang/go/issues/27285

that most likely is one of the reasons found so far.

**Comment by llonchj** [comment]
Thanks for the update @l3pp4rd. 

Still experiencing the same issue: `failed to compile testmain package` which is happening because the pkg name is invalid and for whatever reason adds a `_` before the name: `can't find import: "_/Users/myself/myproject"`.

**Comment by l3pp4rd** [comment]
hi @llonchj could you check if that patch is able to resolve it?

**Comment by llonchj** [comment]
@l3pp4rd The path that exists is "/Users/myself/myproject", but not "_/Users/myself/myproject" (note the _ in the beginning

**Comment by l3pp4rd** [comment]
yes, this patch should handle this, for some reason before go1.11 the import path for go projects outside GOPATH was just a package name, now it became this `"_/Users/myself/myproject"` the patch should replace it with package name, which should work.

**Comment by llonchj** [comment]
@l3pp4rd thanks for the update.

This is the current outcome:

```
failed to compile testmain package: exit status 2 - output: /var/folders/x4/s1l6gz3x7b5fqvbnbfj80zn40000gn/T/go-build015318427/b001/_testmain.go:5:2: can't find import: "myproject"
```
given the contents of `go.mod` file start with...

```
module gitlab.com/myuser/myproject
```

Do you think the import should be `github.com/myuser/myproject`?

**Comment by l3pp4rd** [comment]
hm, OK, will need to try this in more detail, thanks

**Comment by l3pp4rd** [comment]
@llonchj the latest master branch should support it now. if not please reopen
