### ISSUE TITLE
Godog failing with error: invalid packagefile: syntax is "packagefile path=filename"

### ISSUE THREAD

**Issue by Tapanito** [DATA-DOG/godog#156]
**Godog version**
`Godog version is: v0.7.10`

**Golang version**
`go version go1.11.4 linux/amd64`

When trying to run generate step definitions with `godog` I received the following error:
```
failed to compile testmain package: exit status 1 - output: compile: /tmp/godog-1547831401318934106/importcfg.link:30: invalid packagefile: syntax is "packagefile path=filename"
```

I ran all tests in under godog package: none of them failed. Then i tried running `go mod tidy` in case there were some strange imports on my end. Then when I ran `godog` again, the step definitions were generated, but after runing `godog` the second time, I received the same error.

I looked around my go.mod file and I found the following:
```
github.com/DATA-DOG/godog v0.7.9 // indirect
```
Which doesn't match the godog version I'm currently using, I tried down grading to `v0.7.9`, however the behaviour remains the same.

Note, running godog in `GOPATH` works fine, also I'm able to run existing tests with `go test`.

**Comment by Tapanito** [comment]
Hi Gedi, 
I'm looking around a bit more into what's going. The issue is caused by three packages in importcfg.link:

```
packagefile github.com/DATA-DOG/godog/colors=
packagefile github.com/DATA-DOG/godog/gherkin=
packagefile .=
```
The location of their package object is unknown. 

I'm happy to resolve this issue, though I'm a bit out of my depth, I'd appreciate any pointers :)

**Comment by l3pp4rd** [comment]
Found an issue, it is due to the go local cache, it creates a cache for compiled module packages, but godog has no chance to find it, since it does not provide the link to that file in go build tool chain. This may happen when you do not have a `godog` package referenced in any of your **test** files and using a module.

I'll need to investigate how we can find that cached package compiled. or come up with some workaround.

**Comment by ascotan** [comment]
hit this as well

**Comment by aaronc** [comment]
Ran into this as well. Any workaround yet?

**Comment by mec07** [comment]
Also having an issue with this. 
```
go version go1.12 darwin/amd64
```

I'm running this from my `GOPATH`, I put the feature file in a features folder and named the package `features` got the `godog` package included in a test file.
Environment variables of interest:
```
PATH=$GOPATH/bin:$PATH
export GO111MODULE="on"
```

Error message:
```
godog features/activity.feature
failed to compile testmain package: exit status 1 - output: compile: /var/folders/p_/1pp4gq996nd4v1b7tpp4746h0000gn/T/godog-1552413744006212000/importcfg.link:31: invalid packagefile: syntax is "packagefile path=filename"
```

Please let me know if there are any ideas on how to fix this! :)

**Comment by l3pp4rd** [comment]
Hi @mec07 could you produce a minimum test case with godog package included in test.go file and print exact commands? I was not able to reproduce the issue when godog was included in test file, will need to build some debugging details into the command

**Comment by mec07** [comment]
@l3pp4rd Sure, will do. Interestingly enough, I checked out & ran the godog tests from within my `GOPATH` and they failed:
```
$ go test ./...
go: finding github.com/DATA-DOG/go-txdb v0.1.2
go: downloading github.com/DATA-DOG/go-txdb v0.1.2
go: extracting github.com/DATA-DOG/go-txdb v0.1.2
...................................................................... 70
...................................................................... 140
...................................................................... 210
.......................................                                249


60 scenarios (60 passed)
249 steps (249 passed)
0s

Randomized with seed: 1552472006585285000
--- FAIL: TestGodogBuildWithoutSourceNotInGoPath (0.83s)
    builder_test.go:137: failed to compile testmain package: exit status 2 - output: /var/folders/p_/1pp4gq996nd4v1b7tpp4746h0000gn/T/godog-1552472015066750000/_testmain.go:4:2: can't open import: "github.com/DATA-DOG/godog": open /Users/marc/pkg/darwin_amd64/github.com/DATA-DOG/godog.a: no such file or directory

--- FAIL: TestGodogBuildWithoutTestSourceNotInGoPath (0.84s)
    builder_test.go:137: failed to compile testmain package: exit status 2 - output: /var/folders/p_/1pp4gq996nd4v1b7tpp4746h0000gn/T/godog-1552472015895590000/_testmain.go:4:2: can't open import: "github.com/DATA-DOG/godog": open /Users/marc/pkg/darwin_amd64/github.com/DATA-DOG/godog.a: no such file or directory

FAIL
FAIL	github.com/DATA-DOG/godog	14.262s
?   	github.com/DATA-DOG/godog/cmd/godog	[no test files]
?   	github.com/DATA-DOG/godog/colors	[no test files]
?   	github.com/DATA-DOG/godog/examples	[no test files]
ok  	github.com/DATA-DOG/godog/examples/api	0.052s [no tests to run]
ok  	github.com/DATA-DOG/godog/examples/db	0.052s [no tests to run]
ok  	github.com/DATA-DOG/godog/examples/godogs	0.062s [no tests to run]
?   	github.com/DATA-DOG/godog/gherkin	[no test files]
```
There is clearly a problem with package resolution... I'm wondering if it would be better to use the `packages.Load(...)` instead of the custom package searching currently in godog: https://godoc.org/golang.org/x/tools/go/packages

**Comment by l3pp4rd** [comment]
Hi again, I've created a patch in branch [resolve-import](https://github.com/DATA-DOG/godog/tree/resolve-import), this should resolve all cases. could you test it. All my tests seem to work fine.

Though, the workaround, was to produce a temporary file which imports this package. The issue with modules is that golang toolchain does not expose any tools to find module cached package.

I'll merge the patch as soon as few people will confirm that it solves their issues

**Comment by l3pp4rd** [comment]
v0.7.12 should resolve this, reopen in case if any further issues

**Comment by mec07** [comment]
@l3pp4rd sorry for slow response, I've only just looked at it. I'm still having the same issue when I put the file into the features file:
```
$ godog -version
Godog version is: v0.7.12
$ godog features/activity.feature
failed to compile testmain package: exit status 1 - output: compile: /var/folders/p_/1pp4gq996nd4v1b7tpp4746h0000gn/T/godog-1552673817598907000/importcfg.link:23: invalid packagefile: syntax is "packagefile path=filename"
```
Did you test using the test repo I created? Thanks for the help! :)

**Comment by l3pp4rd** [comment]
Update the godog command line tool to latest version

**Comment by mec07** [comment]
@l3pp4rd Ah, great, thanks! You're quite right. This issue is now fixed. It is running when I don't have the test file in the root of the directory. It's only finding the steps when they're in the root, which is a shame, but I can create an issue for that. Thanks for fixing this!
